# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ref', models.CharField(max_length=64)),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Last Edited')),
                ('pics', models.FileField(upload_to=b'')),
                ('description', models.CharField(max_length=255)),
                ('broker_name', models.CharField(max_length=15)),
                ('property_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
