# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pics',
            field=models.FileField(upload_to='/'),
        ),
    ]
