# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_site', '0002_auto_20160526_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='pics',
            field=models.FileField(upload_to='/testdir/'),
        ),
    ]
