# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_site', '0004_auto_20160526_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='radio_array',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='properties',
            unique_together=set([('pics', 'description', 'broker_name', 'property_name', 'phone_number')]),
        ),
    ]
